### ISSUE TITLE
Singularity Hub

### ISSUE THREAD

**Issue by vsoch** [pavel-demin/singularity-ubuntu#1]
Hi @pavel-demin ! I'm the lead developer of Singularity Hub. Last night you issued 64 GET requests to download your container in a short period of time, likely because you ran something in parallel without downloading it first. I want to give you a friendly reminder that the container has a weekly (global) limit of 100, and for the future I'd like to ask you to pull the container first:

```bash
singularity pull shub://pavel-demin/singularity-ubuntu:1804
```
and then interact with the container binary

```bash
singularity exec singularity_ubuntu_1804.sif ...
singularity run singularity_ubuntu_1804.sif ...
```
Please confirm that you received this, and will adjust future interaction. Thank you!

**Comment by pavel-demin** [comment]
I'm very surprised that you're contacting me about the Singularity Hub problems and accusing me of some doings without any real evidence for such accusations.

If your service isn't production ready, then just close it for public access.

> Last night you issued 64 GET requests to download your container in a short period of time, likely because you ran something in parallel without downloading it first.

What makes you think that it was me who issued the 64 GET requests?

I've created this repository when I tested Singularity Hub one year ago. Currently, I'm not using this container. I have no idea who is using it.

> Please confirm that you received this, and will adjust future interaction.

If you plan to continue communication in the same tone, then I am not at all interested in this continuation.

If your product isn't capable to provide more than 100 downloads per week, then I'd suggest you, as a "lead developer", to concentrate on the development of your product and stop wasting your time annoying your users with your unfounded accusations.

I've just checked you GitHub history, and I've found many similar issues that you've created:

https://github.com/willgpaik/qt5_aci/issues/1
https://github.com/nickjer/singularity-rstudio/issues/7
https://github.com/edraizen/SingularityTorch/issues/2
https://github.com/JCSDA/singularity/issues/9
https://github.com/jemunro/containers/issues/2
https://github.com/h3abionet/chipimputation/issues/18

What a waste of time!

**Comment by vsoch** [comment]
It's an academic service, and I do my best. You are correct that I don't know the source of the GETs (without knowing your IP address) and in most cases, it is in fact the creator of the container that did the requests. The inquiry was a polite effort to help you, in the case that it was you, and you might be surprised to hit the limit. I work extremely hard to maintain this service, and your response is very hurtful.

**Comment by pavel-demin** [comment]
I've removed my containers from Singularity Hub and I'll shortly remove the corresponding GitHub repositories.
